sudo: false
dist: trusty
language: php
php:
    - 5.6
    - 7
env:
    global:
        - CORE_BRANCH=master
        - NIGHTLY=FALSE
    matrix:
        - DB=pgsql

branches:
  only:
    - master
    - /^stable\d+(\.\d+)?$/
    - /^v\d++(\.\d+)?+(\.\d+)?+(\.\d+)?$/

matrix:
    allow_failures:
        - env: DB=pgsql CORE_BRANCH=master
    include:
        - php: 5.6
          env:  DB=pgsql CORE_BRANCH=master
        - php: 7
          env:  DB=pgsql CORE_BRANCH=stable11
    fast_finish: true

before_install:
    - export DISPLAY=:99.0
    - sh -e /etc/init.d/xvfb start
    - nvm install 5.6
    - npm install -g npm@latest
    - make
    - make appstore
    # install nextcloud
    - cd ../
    - git clone https://github.com/nextcloud/server.git --recursive --depth 1 -b $CORE_BRANCH core
    - mv nextcloud-contacts core/apps/contacts

before_script:
    - if [[ "$DB" == 'pgsql' ]]; then createuser -U travis -s oc_autotest; fi
    - if [[ "$DB" == 'mysql' ]]; then mysql -u root -e 'create database oc_autotest;'; fi
    - if [[ "$DB" == 'mysql' ]]; then mysql -u root -e "CREATE USER 'oc_autotest'@'localhost' IDENTIFIED BY '';"; fi
    - if [[ "$DB" == 'mysql' ]]; then mysql -u root -e "grant all on oc_autotest.* to 'oc_autotest'@'localhost';"; fi
    # fill nextcloud with default configs and enable contacts
    - cd core
    - mkdir data
    - ./occ maintenance:install --database-name oc_autotest --database-user oc_autotest --admin-user admin --admin-pass admin --database $DB --database-pass=''
    - ./occ app:enable contacts
    - ./occ background:cron  # enable default cron
    - php -S localhost:8080 &
    - cd apps/contacts

script:
    - make test

after_failure:
    - cat ../../data/nextcloud.log

after_success:
    # codecov has issues when not run exactly in the cloned folder on travis, so
    # revert everything
    - cd ../../../
    - mv core/apps/contacts .
    - cd contacts
    - node_modules/codecov/bin/codecov

addons:
    firefox: "latest"
